import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String formatter(int chicken, int hamburger, int noodle) {
        // promo1: half price for chicken and noodle
        // promo2: reach 30 -$6
        int totalPrice = chicken * 18 + hamburger * 6 + noodle * 8;
        int promo1Price = chicken * 18 / 2 + hamburger * 6 + noodle * 8 / 2;
        int promo2Price = totalPrice >= 30 ? totalPrice - 6 : totalPrice;
        int discount = 0;
        int finalPrice = totalPrice;
        if (promo1Price < totalPrice) {
            discount = 1;
            finalPrice = promo1Price;
        }
        if (promo2Price < totalPrice && promo2Price < promo1Price) {
            discount = 2;
            finalPrice = promo2Price;
        }
        return "============= Order details =============\n" +
                (chicken > 0 ? "Braised chicken x " + chicken + " = " + chicken * 18 + " yuan\n" : "") +
                (hamburger > 0 ? "Chinese hamburger x " + hamburger + " = " + hamburger * 6 + " yuan\n" : "") +
                (noodle > 0 ? "Cold noodles x " + noodle + " = " + noodle * 8 + " yuan\n" : "") +
                "-----------------------------------\n" +
                (discount == 0 ? ""
                        : "Promotion used:\n" +
                                (discount == 1
                                        ? "Half price for certain dishes (Braised chicken，Cold noodles)，saving "
                                                + (totalPrice - promo1Price) + " yuan\n"
                                        : "满30减6 yuan，saving 6 yuan\n")
                                +
                                "-----------------------------------\n")
                +
                "Total：" + finalPrice + " yuan\n" +
                "===================================";
    }

    public String bestCharge(List<String> inputs) {
        int chicken = 0, hamburger = 0, noodle = 0;
        for (String order : inputs) {
            if (order.startsWith("ITEM0001")) {
                chicken += Integer.parseInt(order.split(" x ")[1]);
            }
            if (order.startsWith("ITEM0013")) {
                hamburger += Integer.parseInt(order.split(" x ")[1]);
            }
            if (order.startsWith("ITEM0022")) {
                noodle += Integer.parseInt(order.split(" x ")[1]);
            }
        }
        return formatter(chicken, hamburger, noodle);
    }
}
